name: Deploy
on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Test SSH Connection
      run: nc -zv simplebank.my.id 22

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER@$HOST" << 'EOF'
          echo "Connected to the server successfully."
          cd ~/FSW-Backend || { echo "Failed to change directory"; exit 1; }
          git pull origin development || { echo "Failed to pull from Git"; exit 1; }
          yarn install || { echo "Failed to install dependencies"; exit 1; }
          pm2 restart all || { echo "Failed to restart PM2"; exit 1; }
          sudo systemctl reload nginx || { echo "Failed to reload Nginx"; exit 1; }
        EOF

    - name: Notify Success
      if: success()
      run: echo "Deployment successful!"

    - name: Notify Failure
      if: failure()
      run: echo "Deployment failed!"