name: Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn install

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      run: |
        set -x
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $HOST >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$USER@$HOST" << 'EOF'
          cd ~/FSW-Backend || exit 1
          git pull origin development || exit 1
          yarn install || exit 1
          pm2 restart all || exit 1
          sudo systemctl reload nginx || exit 1
        EOF

    - name: Notify Success
      if: success()
      run: echo "Deployment successful!"

    - name: Notify Failure
      if: failure()
      run: echo "Deployment failed!"